# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
np.__version__

'2.1.3'

#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
null_vector =np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [6]:
array = np.zeros(10)
memory_size = array.nbytes
print(f"Memory size of the array: {memory_size}bytes")

Memory size of the array: 80bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [7]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its or

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [8]:
null_vector = np.zeros(10)
null_vector[4]=1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [9]:
vector= np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [10]:
vector = np.arange(10,50)
reversed_vector = vector[::-1]
print("original vector:",vector)
print("Reversed vector:",reversed_vector)

original vector: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
Reversed vector: [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [11]:
matrix = np.arange(9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [12]:
array = [1,2,0,0,4,0]
non_zero_indices = [i for i,val in enumerate(array)if val != 0]
print("indices of non-zero elements:",non_zero_indices)


indices of non-zero elements: [0, 1, 4]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [13]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [14]:
random_array = np.random.rand(3,3,3)
print(random_array)

[[[0.06200289 0.35807422 0.10684602]
  [0.88869145 0.3328511  0.88372748]
  [0.89973762 0.25540871 0.82917933]]

 [[0.71511799 0.57915782 0.53346227]
  [0.39997543 0.59700741 0.69599494]
  [0.12979483 0.80925947 0.14471773]]

 [[0.02146537 0.18322554 0.04161583]
  [0.25584821 0.28746493 0.08376578]
  [0.7325937  0.74040041 0.15518507]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [15]:
random_array = np.random.rand(10,10)
min_value = np.min(random_array)
max_value = np.max(random_array)
print("random 10*10 array:\n",random_array)
print("minimum value:" ,min_value)
print("maximum value:",max_value)

random 10*10 array:
 [[0.5166722  0.63188229 0.87518672 0.50990037 0.71949745 0.75095295
  0.41056713 0.2566988  0.36853992 0.34763297]
 [0.81883621 0.33363544 0.95317999 0.98587043 0.91730939 0.24797048
  0.3401402  0.52496304 0.62778814 0.19720964]
 [0.64309431 0.67111647 0.23860531 0.79195652 0.01129613 0.0696318
  0.79133999 0.73677406 0.70664362 0.64443121]
 [0.858009   0.93924531 0.29526125 0.93827215 0.45059348 0.50370159
  0.48156168 0.27188089 0.93623657 0.01280015]
 [0.20897249 0.19959721 0.70144612 0.40877277 0.36575142 0.15808652
  0.20996405 0.74158765 0.28035613 0.04134404]
 [0.98917349 0.17499517 0.71953161 0.49605254 0.33836729 0.47071016
  0.98362456 0.49731774 0.60769992 0.42214337]
 [0.19319192 0.98515457 0.32696273 0.33597361 0.43516874 0.8919787
  0.37846138 0.59825804 0.27480071 0.83737619]
 [0.57836532 0.46502568 0.54174392 0.62788961 0.04085553 0.87993316
  0.37928351 0.74528964 0.74472349 0.81156963]
 [0.20922436 0.54165139 0.04232963 0.66701592 0.39445702 0.92

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [16]:
z = np.random.random(30)
m = z.mean()
print(m)

0.5516215767012465


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [17]:
z = np.ones((10,10))
z[1:-1,:-1] = 0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [20]:
z = np.ones((5,5))
z = np.pad(z, pad_width=1, mode='constant', constant_values=0)
print(z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [22]:
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [23]:
z = np.diag(1+np.arange(4),k=-1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [24]:
z = np.zeros((8,8),dtype=int)
z[1::2,::2] = 1
z[::2,1::2] = 1
print(z)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
print(np.unravel_index(99,(6,7,8)))

(np.int64(1), np.int64(5), np.int64(3))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [27]:
z = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [29]:
z = np.random.random((5,5))
z = (z - np.mean (z)) / (np.std(z))
print(z)

[[-0.88751147  0.01602908  0.32207405 -0.53402803 -0.00266254]
 [-1.14348654  1.07807001  1.32563606 -0.92580678  0.77793495]
 [-0.27974807 -1.28924412 -0.82492875 -1.35620517  1.14045486]
 [ 1.21707107 -1.37101573  1.35519007  0.73342234 -0.8353052 ]
 [ 1.38154175  1.10182837 -0.53171669 -1.37944713  0.91185361]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [31]:
color = np.dtype([("r",np.ubyte),("g",np.ubyte),("b",np.ubyte),("a",np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [34]:
z = np.dot(np.ones((5,3)),np.ones((3,2)))
print(z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [35]:
z = np.arange(11)
z[(3<z) & (z<8)] *=-1
print(z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [36]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [46]:
result = 2.0 ** -2  # Correct usage
print(result)  # Output: 0.25



0.25


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [47]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


C:\Users\Chandana\AppData\Local\Temp\ipykernel_14276\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\Chandana\AppData\Local\Temp\ipykernel_14276\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\Chandana\AppData\Local\Temp\ipykernel_14276\3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [49]:
z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(z)),z))
print(np.where(z>0,np.ceil(z),np.floor(z)))

[ 5. -6.  6.  7. -3. -2. -4.  4.  4. -6.]
[ 5. -6.  6.  7. -3. -2. -4.  4.  4. -6.]


#### 30. How to find common values between two arrays? (★☆☆)

In [50]:
z1 = np.random.randint(0,10,10)
z2 = np.random.randint(0,10,10)
print(np.intersect1d(z1,z2))

[0 1 4 5 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [53]:
defaults = np.seterr(all="ignore")
z = np.ones(1) / 0
np.seterr(**defaults)

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [54]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\Chandana\AppData\Local\Temp\ipykernel_14276\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [58]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)


Yesterday: 2024-12-07
Today: 2024-12-08
Tomorrow: 2024-12-09


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [60]:
z = np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [61]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [63]:
z = np.random.uniform(0,10,10)
print(z - z%1)
print(z // 1)
print(np.floor(z))
print(z.astype(int))
print(np.trunc(z))

[0. 3. 2. 5. 9. 2. 3. 1. 4. 7.]
[0. 3. 2. 5. 9. 2. 3. 1. 4. 7.]
[0. 3. 2. 5. 9. 2. 3. 1. 4. 7.]
[0 3 2 5 9 2 3 1 4 7]
[0. 3. 2. 5. 9. 2. 3. 1. 4. 7.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [64]:
z = np.zeros((5,5))
z +=np.arange(5)
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [66]:
def generate():
    for x in range(10):
        yield x
z = np.fromiter(generate(),dtype=float,count=-1)
print(z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [69]:
z = np.linspace(0,1,11,endpoint=False)[1:]
print(z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [70]:
z = np.random.random(10)
print(z)

[0.14315612 0.6706496  0.31777444 0.92593985 0.07173051 0.18584409
 0.63940114 0.97028529 0.65095375 0.16307732]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [73]:
z = np.arange(10)
np.add.reduce(z)

np.int64(45)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [74]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


#### 43. Make an array immutable (read-only) (★★☆)

In [79]:
array = np.array([1, 2, 3, 4, 5])
array.flags.writeable = False
try:
    array[0] = 10
except ValueError as e:
    print(f"Error: {e}")

Error: assignment destination is read-only


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [81]:
z = np.random.random((10,2))
X,Y = z[:,0],z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.15399889 1.11666108 0.58729662 0.59132892 1.08087427 1.06962721
 0.745078   0.84780817 0.25488023 0.641567  ]
[0.01692052 0.79999163 1.04845837 0.08499592 0.49459834 0.77204127
 0.38336436 0.26644897 1.34791783 0.81669821]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [82]:
z = np.random.random(10)
z[z.argmax()]=0
print(z)

[0.73294821 0.58400555 0.59567316 0.84678072 0.56608373 0.30055523
 0.27448781 0.         0.46941938 0.4667725 ]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [86]:
z = np.zeros((5,5),[('x',float),('y',float)])
z['x'], z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [87]:
x = np.arange(8)
y = x + 0.5
c = 1.0 / np.subtract.outer(x,y)
print(np.linalg.det(c))


3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [88]:
for dtype in [np.int8,np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
for dtype in [np.float32,np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
-128
-2147483648
-9223372036854775808
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [89]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [90]:
arr = np.array([1, 3, 7, 10,13])
scalar = 8
closest_value = arr[np.abs(arr - scalar).argmin()]

print(f"The closest value to {scalar} is {closest_value}")

The closest value to 8 is 7


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [91]:
dtype = [('position', '2f4'), ('color', '3f4')]
structured_array = np.array([((1.0, 2.0), (255.0, 0.0, 0.0)), ((3.0, 4.0), (0.0, 255.0, 0.0)), ((5.0, 6.0), (0.0, 0.0, 255.0))], dtype=dtype)
print(structured_array)

[([1., 2.], [255.,   0.,   0.]) ([3., 4.], [  0., 255.,   0.])
 ([5., 6.], [  0.,   0., 255.])]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [95]:
coordinates = np.random.random((100, 2)) * 10  
distances = np.sqrt(np.sum((coordinates[:, np.newaxis] - coordinates)**2, axis=2))
print(distances)

[[0.         4.30689078 4.04357274 ... 3.91889309 3.04576928 3.02676386]
 [4.30689078 0.         2.17137638 ... 2.07579159 4.18839716 4.44891868]
 [4.04357274 2.17137638 0.         ... 0.14966056 2.43997657 2.72633628]
 ...
 [3.91889309 2.07579159 0.14966056 ... 0.         2.4228435  2.70813002]
 [3.04576928 4.18839716 2.43997657 ... 2.4228435  0.         0.28654442]
 [3.02676386 4.44891868 2.72633628 ... 2.70813002 0.28654442 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [96]:
arr = np.array([1.2, 2.5, 3.8, 4.1], dtype=np.float32)
arr[:] = arr.astype(np.int32)
print(arr)


[1. 2. 3. 4.]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [98]:
from io import StringIO
s = StringIO('''1,3,3,4,5,6,,,7,8,,9,10,11''')
z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(z)

AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [99]:
arr = np.array([10, 20, 30, 40, 50])
for index, value in np.ndenumerate(arr):
    print(f"Index: {index}, Value: {value}")


Index: (0,), Value: 10
Index: (1,), Value: 20
Index: (2,), Value: 30
Index: (3,), Value: 40
Index: (4,), Value: 50


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [100]:
x,y = np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
D = np.sqrt(x*x+y*y)
sigma,mu = 1.0,0.0
g = np.exp(-(D-mu)**2 / (2.0 * sigma**2))
print(g)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [102]:
n = 10
p = 3
z = np.zeros((n,n))
np.put(z,np.random.choice(range(n*n),p, replace=False),1)
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [103]:
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])
row_means = np.mean(matrix, axis=1, keepdims=True)
result = matrix - row_means
print(result)


[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


#### 59. How to sort an array by the nth column? (★★☆)

In [105]:
z = np.random.randint(0,10,(3,3))
print(z)
print(z[z[:,1].argsort()])

[[3 0 5]
 [0 1 7]
 [3 1 8]]
[[3 0 5]
 [0 1 7]
 [3 1 8]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [106]:
array = np.array([[1, 2, 3],
                  [4, np.nan, 6],
                  [7, 8, 9]])
has_null_columns = np.any(np.isnan(array), axis=0)
print("Null columns:", has_null_columns)


Null columns: [False  True False]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [108]:
arr = np.array([1, 3, 7, 10, 15, 20])
value = 12
differences = np.abs(arr - value)
index = np.argmin(differences)
nearest_value = arr[index]
print(f"The nearest value to {value} is {nearest_value}")

The nearest value to 12 is 10


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [110]:
A = np.array([[1, 2, 3]])  
B = np.array([[4], [5], [6]])  
it = np.nditer([A, B], flags=['multi_index'])
for x, y in it:
    print(f"Sum of {x} and {y} is {x + y}")

Sum of 1 and 4 is 5
Sum of 2 and 4 is 6
Sum of 3 and 4 is 7
Sum of 1 and 5 is 6
Sum of 2 and 5 is 7
Sum of 3 and 5 is 8
Sum of 1 and 6 is 7
Sum of 2 and 6 is 8
Sum of 3 and 6 is 9


#### 63. Create an array class that has a name attribute (★★☆)

In [111]:
class NamedArray(np.ndarray):
    def __new__(cls, shape, dtype=float, name="Unnamed Array"):
        # Create a new instance of np.ndarray
        obj = np.ndarray.__new__(cls, shape, dtype=dtype)
        # Add the name attribute
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        # This ensures that the name attribute is preserved in derived arrays
        if obj is None: return
        self.name = getattr(obj, 'name', "Unnamed Array")

# Example usage:
arr = NamedArray((2, 3), dtype=int, name="My Array")

print(f"Array:\n{arr}")
print(f"Array name: {arr.name}")

Array:
[[-11  -9  -5]
 [ -2   3   8]]
Array name: My Array


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [113]:
z = np.ones(10)
I = np.random.randint(0,len(z),20)
z += np.bincount(I, minlength=len(z))
print(z)


[5. 1. 2. 3. 4. 2. 3. 3. 2. 5.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [116]:
X = np.array([10, 20, 30, 40, 50])  
I = np.array([0, 2, 2, 3, 1])      
F = np.zeros(np.max(I) + 1)  
np.add.at(F, I, X)
print("Accumulated array F:", F)


Accumulated array F: [10. 50. 50. 40.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [117]:
w, h = 4, 4  
image = np.random.randint(0, 256, size=(w, h, 3), dtype=np.uint8)
image_reshaped = image.reshape(-1, 3)
unique_colors = np.unique(image_reshaped, axis=0)
print(f"Number of unique colors: {len(unique_colors)}")

Number of unique colors: 16


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [118]:
array = np.random.randint(0, 10, size=(2, 3, 4, 5))  
result = np.sum(array, axis=(-2, -1))
print("Original Array Shape:", array.shape)
print("Resulting Array Shape:", result.shape)
print(result)

Original Array Shape: (2, 3, 4, 5)
Resulting Array Shape: (2, 3)
[[ 70  94  83]
 [ 91  96 102]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [119]:
D = np.array([10, 20, 30, 40, 50, 60, 70])
S = np.array([0, 1, 0, 1, 0, 1, 1])  
unique_indices, counts = np.unique(S, return_counts=True)
subset_sums = np.array([D[S == idx].sum() for idx in unique_indices])
subset_means = subset_sums / counts
print("Subset Means:", subset_means)

Subset Means: [30.  47.5]


#### 69. How to get the diagonal of a dot product? (★★★)


In [120]:
A = np.array([[1, 2], [3, 4], [5, 6]])
B = np.array([[7, 8], [9, 10]])
dot_product = np.dot(A, B.T)
diagonal = np.diag(dot_product)

print("Dot Product Matrix:\n", dot_product)
print("Diagonal of Dot Product:", diagonal)


Dot Product Matrix:
 [[ 23  29]
 [ 53  67]
 [ 83 105]]
Diagonal of Dot Product: [23 67]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [124]:
vec = np.array([1, 2, 3, 4,5])
new_vec = np.zeros(len(vec) + (len(vec) - 1) * 3, dtype=int)
new_vec[::4] = vec

print(new_vec)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [125]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A*B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [126]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [127]:

triangles = np.array([ [0, 1, 2],[2, 3, 4],[0, 2, 4],[1, 3, 5],[0, 1, 3],[1, 2, 5],[2, 4, 6],[3, 5, 6],[0, 5, 6],[1, 4, 6]])
line_segments = set()
for triangle in triangles:
    for i in range(3):
        for j in range(i+1, 3):
            segment = tuple(sorted([triangle[i], triangle[j]]))
            line_segments.add(segment)
unique_line_segments = list(line_segments)

print("Unique line segments:")
print(unique_line_segments)


Unique line segments:
[(np.int64(3), np.int64(4)), (np.int64(4), np.int64(6)), (np.int64(0), np.int64(2)), (np.int64(0), np.int64(5)), (np.int64(1), np.int64(6)), (np.int64(2), np.int64(5)), (np.int64(1), np.int64(3)), (np.int64(5), np.int64(6)), (np.int64(3), np.int64(6)), (np.int64(0), np.int64(1)), (np.int64(2), np.int64(4)), (np.int64(1), np.int64(2)), (np.int64(0), np.int64(4)), (np.int64(1), np.int64(5)), (np.int64(3), np.int64(5)), (np.int64(0), np.int64(3)), (np.int64(1), np.int64(4)), (np.int64(0), np.int64(6)), (np.int64(2), np.int64(3)), (np.int64(2), np.int64(6))]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [130]:
C = np.array([2, 3, 1, 0, 4])  
A = np.concatenate([np.full(count, i) for i, count in enumerate(C)])
print("Generated Array A:", A)
print("Bincount of A:", np.bincount(A))


Generated Array A: [0 0 1 1 1 2 4 4 4 4]
Bincount of A: [2 3 1 0 4]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [131]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
window_size = 3
window = np.ones(window_size) / window_size
moving_avg = np.convolve(arr, window, mode='valid')
print("Array:", arr)
print(f"Moving average with window size {window_size}:", moving_avg)

Array: [ 1  2  3  4  5  6  7  8  9 10]
Moving average with window size 3: [2. 3. 4. 5. 6. 7. 8. 9.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [132]:
Z = np.array([1, 2, 3, 4, 5, 6, 7, 8])
rows = len(Z) - 2  
result = np.array([Z[i:i+3] for i in range(rows)])

print("Original array Z:", Z)
print("Resulting 2D array:")
print(result)

Original array Z: [1 2 3 4 5 6 7 8]
Resulting 2D array:
[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [134]:
z = np.random.randint(0,2,100)
np.logical_not(z,out=z)
z = np.random.uniform(-1.0,1.0,100)
np.negative(z,out=z)

array([ 0.1728517 ,  0.45283311,  0.06420247, -0.59501489, -0.06195935,
        0.6394824 , -0.55909019, -0.11070291,  0.31055683, -0.38146673,
        0.22397068,  0.8063992 ,  0.79067208, -0.19833169,  0.4735108 ,
       -0.34209732, -0.4856904 , -0.94904956,  0.57618031,  0.63936532,
       -0.87001273, -0.51783246,  0.55822749, -0.08422412, -0.03945531,
       -0.81384922,  0.87772603, -0.32216202, -0.54090376, -0.5096034 ,
       -0.15586116,  0.73626589, -0.63412802, -0.44474096,  0.22677199,
       -0.29037025, -0.45397272,  0.10134037, -0.58998741, -0.67936285,
        0.63126014, -0.90809039,  0.09611437,  0.88712085, -0.2798625 ,
       -0.81309369, -0.30267969,  0.82855731,  0.13231111, -0.53309611,
        0.23566902,  0.34207463,  0.60839707, -0.14933626, -0.373809  ,
        0.32274967,  0.56992266,  0.39364447,  0.65260379, -0.89878697,
        0.56955219,  0.59148728,  0.05657329, -0.12192689,  0.18122936,
        0.80113969,  0.90492028, -0.17572582,  0.78093379, -0.24

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [139]:
P0 = np.array([[0, 0], [1, 1], [2, 3]])  
P1 = np.array([[4, 0], [1, 4], [3, 4]])  
p = np.array([2, 2])  # Point p
def point_to_line_distance(P0, P1, p):
    distances = []
    for i in range(len(P0)):
        x0, y0 = P0[i]
        x1, y1 = P1[i]
        xp, yp = p
        numerator = abs((x1 - x0) * (y0 - yp) - (x0 - xp) * (y1 - y0))
        denominator = np.sqrt((x1 - x0)**2 + (y1 - y0)**2)
        distance = numerator / denominator
        distances.append(distance)
    return np.array(distances)
distances = point_to_line_distance(P0, P1, p)
print("Distances from point p to each line:", distances)


Distances from point p to each line: [2.         1.         0.70710678]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [141]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([Distance(P0,P1,p_i) for p_i in p]))

NameError: name 'Distance' is not defined

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [145]:
import numpy as np

def extract_subarray(arr, center, shape, fill=0):
    """
    Extract a subarray from `arr` with a fixed `shape` centered on `center` element.
    Pads with `fill` value if necessary.

    Parameters:
    - arr: The input array.
    - center: The index (tuple) of the center element.
    - shape: The shape of the subarray to extract.
    - fill: The value to pad with (default is 0).

    Returns:
    - A subarray with the specified shape, centered around the center element, padded if necessary.
    """
    # Get the dimensions of the original array
    arr_shape = np.array(arr.shape)

    # Compute the half-size of the subarray (assuming shape is odd for simplicity)
    half_shape = np.array(shape) // 2

    # Create slices for each dimension
    slices = []
    for i in range(len(arr_shape)):
        start = center[i] - half_shape[i]
        end = center[i] + half_shape[i] + 1

        # Handle padding (check if start/end is outside the original array bounds)
        if start < 0:
            slices.append(slice(0, end))
        elif end > arr_shape[i]:
            slices.append(slice(start, arr_shape[i]))
        else:
            slices.append(slice(start, end))
    
    # Extract the subarray using slicing
    subarray = arr[tuple(slices)]

    # Pad the result if the subarray doesn't match the requested shape
    pad_width = [(0, max(0, shape[i] - subarray.shape[i])) for i in range(len(shape))]
    subarray_padded = np.pad(subarray, pad_width, mode='constant', constant_values=fill)

    return subarray_padded

# Example usage:
arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20],
                [21, 22, 23, 24, 25]])

center = (2, 2)  # Centered on element arr[2,2] (which is 13)
shape = (3, 3)   # Extract a 3x3 subarray
fill_value = 0   # Fill with 0 if padding is required

subarray = extract_subarray(arr, center, shape, fill=fill_value)
print("Extracted Subarray:")
print(subarray)


Extracted Subarray:
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [ ]:
Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
window_size = 4
R = np.lib.stride_tricks.sliding_window_view(Z, window_size)
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [148]:
rank = np.linalg.matrix_rank(z)
print(rank)

1


#### 83. How to find the most frequent value in an array?

In [150]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

1


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [153]:
matrix = np.random.rand(10, 10)
blocks = np.lib.stride_tricks.sliding_window_view(matrix, (3, 3))
print("Shape of blocks:", blocks.shape)
first_block = blocks[0, 0]
print("First 3x3 block:\n", first_block)


Shape of blocks: (8, 8, 3, 3)
First 3x3 block:
 [[0.23487112 0.94587453 0.63982664]
 [0.57767434 0.90810501 0.94698181]
 [0.09514493 0.32072068 0.38352713]]


#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [154]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)


[[ 7  8  9  7  7]
 [ 8  4 12 15  8]
 [ 9 12  8 42  2]
 [ 7 15 42  4  7]
 [ 7  8  2  7  1]]


#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [155]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)



[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [156]:
array = np.random.rand(16, 16)
block_size = 4
block_sum = array.reshape(16 // block_size, block_size, 16 // block_size, block_size).sum(axis=(1, 3))

print("Original array:\n", array)
print("\nBlock-sum array:\n", block_sum)

Original array:
 [[0.82181451 0.02036564 0.6398239  0.02262917 0.185033   0.82088545
  0.63652216 0.55683429 0.74990196 0.11514254 0.25652643 0.2425359
  0.76097169 0.94555359 0.59047453 0.93838492]
 [0.67574675 0.59288886 0.70247386 0.0605922  0.40112488 0.44402344
  0.92588079 0.25840031 0.92488321 0.58136658 0.69039613 0.4366515
  0.64850936 0.2478203  0.65567527 0.28323127]
 [0.55919659 0.50874038 0.15997258 0.81753416 0.38537108 0.51203036
  0.42764721 0.47079117 0.39193728 0.98034393 0.13217754 0.6388763
  0.48164914 0.24213896 0.92043422 0.34500506]
 [0.41152324 0.30170029 0.15665518 0.6353524  0.41919103 0.53128116
  0.55181902 0.62231721 0.93449582 0.25754727 0.26050498 0.66592816
  0.34454516 0.19041881 0.6132807  0.35546022]
 [0.21034746 0.35495161 0.90580382 0.68751411 0.40292512 0.29717454
  0.20562874 0.26552668 0.75482495 0.54643391 0.11443506 0.8480982
  0.12663106 0.15996381 0.39074772 0.7451827 ]
 [0.82165995 0.888073   0.18979063 0.68547574 0.68585255 0.50646293
  0.

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [157]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [158]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])
print (Z[np.argpartition(-Z,n)[:n]])


[9995 9996 9997 9998 9999]
[9999 9998 9997 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [159]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))


[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [162]:
Z = np.array([("Hello", 2.5, 3),("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, names='col1, col2, col3', formats = 'S8, f8, i8')
print(R)


[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


C:\Users\Chandana\AppData\Local\Temp\ipykernel_14276\1156662623.py:2: DeprecationWarning: numpy.core is deprecated and has been renamed to numpy._core. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.records.
  R = np.core.records.fromarrays(Z.T, names='col1, col2, col3', formats = 'S8, f8, i8')


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [163]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

997 ms ± 48.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
423 ms ± 61.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
213 ms ± 18.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [164]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 4 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [165]:
Z = np.random.randint(0,5,(10,3))
print(Z)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)


[[2 4 2]
 [1 2 2]
 [1 1 1]
 [2 4 2]
 [0 0 4]
 [1 0 4]
 [4 0 3]
 [3 0 3]
 [4 0 2]
 [3 1 1]]
[[2 4 2]
 [1 2 2]
 [2 4 2]
 [0 0 4]
 [1 0 4]
 [4 0 3]
 [3 0 3]
 [4 0 2]
 [3 1 1]]
[[2 4 2]
 [1 2 2]
 [2 4 2]
 [0 0 4]
 [1 0 4]
 [4 0 3]
 [3 0 3]
 [4 0 2]
 [3 1 1]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [166]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])


[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [167]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 1]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [168]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B)    

array([[0.52700237, 0.61386304, 0.25683249, 0.24903087, 0.29084404,
        0.50821775, 0.64964843, 0.23944152, 0.10427106, 0.23221729],
       [0.32154531, 0.3745425 , 0.15670382, 0.15194373, 0.17745563,
        0.31008406, 0.3963766 , 0.14609289, 0.06361996, 0.1416851 ],
       [0.1066986 , 0.12428469, 0.05199913, 0.05041959, 0.05888522,
        0.1028954 , 0.13152991, 0.0484781 , 0.02111105, 0.04701546],
       [0.09287735, 0.10818542, 0.0452634 , 0.04388847, 0.0512575 ,
        0.08956681, 0.11449214, 0.04219847, 0.01837643, 0.0409253 ],
       [0.69870663, 0.81386764, 0.34051187, 0.33016838, 0.38560483,
        0.67380173, 0.86131238, 0.31745469, 0.13824393, 0.30787672],
       [0.53879017, 0.62759371, 0.26257722, 0.2546011 , 0.29734953,
        0.51958538, 0.66417954, 0.24479726, 0.10660336, 0.23741145],
       [0.24081415, 0.2805052 , 0.11735981, 0.11379485, 0.13290141,
        0.2322305 , 0.29685736, 0.10941299, 0.04764674, 0.10611187],
       [0.65483226, 0.76276189, 0.3191298

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [170]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)
y_int = np.interp(r_int, r, y)


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [171]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [ ]:
X = np.random.randn(100) 
N = 1000
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.20519404  0.1671509 ]
